require("pwalleni.plugins-setup")
require("pwalleni.core.options")
require("pwalleni.core.keymaps")
require("pwalleni.core.colorscheme")
require("pwalleni.plugins.comment")
require("pwalleni.plugins.lualine")
require("pwalleni.plugins.telescope")
require("pwalleni.plugins.nvim-cmp")
require("pwalleni.plugins.lsp.mason")
require("pwalleni.plugins.lsp.lspsaga")
require("pwalleni.plugins.lsp.lspconfig")
require("pwalleni.plugins.lsp.null-ls")
-- require("pwalleni.plugins.autopairs")
require("pwalleni.plugins.treesitter")
require("pwalleni.plugins.gitsigns")
